accept as input SD files with 3D conformations (reference and library compounds)
healx/lig3dlens pull request #20
Opened 2024-05-16 15:29 UTC by bill-tatsis

Lig3DLens can now accept as input files, for both reference and library molecules, that contain already generated 3D conformers 🐢. It omits the conformer generation step and proceeds directly to the 3D alignment/scoring process.

2024-05-23 10:52 UTC, mps-hlx approved these changes
Thanks for the really helpful comment, extra documentation, and special effort with the type hints! 

It all looks good to me.

2024-05-23 11:00 UTC, danodonovan requested changes
@bill-tatsis Sorry - because the CI wasn't green-lit I assumed the PR wasn't yet ready for review. 

The fix suggested should get your further along the CI

2024-05-23 11:00 UTC, danodonovan commented on lig3dlens/alignment.py
> +from typing import Optional, Dict, Generator, Tuple
This line is causing the CI to fail, we can either manually correct ... or running `isort` will fix this for you; 

```
$ isort --profile black lig3dlens tests setup.py
```

2024-07-08 08:44 UTC, danodonovan approved these changes

2024-07-08 08:50 UTC, merged